---
- hosts: localhost
  tasks:
  - name: Create Sec Groups
    ec2_group:
      name: Allow_80   #This playbook is for allowing port 80 for 0.0.0.0/0
      description: sg with rule descriptions
      #vpc_id: vpc-xxxxxxxx
      #profile: "{{ aws_profile }}"
      #state: absent
      region: us-east-1
      rules:
        - proto: tcp
          ports:
          - 80
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on port 80
    