---
- hosts: localhost
  vars_files: 
  - vpc_info.yaml
  tasks: 
  - name: create a VPC with dedicated tenancy
    ec2_vpc_net:
      name:          "{{name}}"
      cidr_block:    "{{cidr_block}}"
      region:        "{{region}}"
      #state: absent
